/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const viewData = {
	id: "Vacations-Approval",
	label: "Vacations Approving",
	link: "/services/web/vacation-approval/index.html",
	perspectiveName: "Vacations",
};

if (typeof exports !== 'undefined') {
	exports.getDialogWindow = function () {
		return viewData;
	}
}